openapi: 3.1.0
paths:
  /:
    get:
      operationId: getHealthStatus
      parameters: []
      responses:
        "200":
          description: Health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        default:
          description: Default error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
      summary: Get the health status of the application
      tags:
        - health
      x-speakeasy-group: health
      x-speakeasy-name-override: get
  /v1/organizations/{organizationId}/workspaces:
    post:
      description: Create a new Workspace in the specified Organization.
      operationId: v1.workspaces.createWorkspace
      parameters:
        - name: organizationId
          required: true
          in: path
          description: The <code>id</code> of the Organization where you want to create the Workspace.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                workspaceId:
                  type: string
                  description: Unique identifier for the workspace
                  minLength: 4
                  maxLength: 41
                  pattern: ^[a-z0-9]*$
                  example: main
                alias:
                  type: string
                  description: User-friendly alias for the workspace
                  example: Production Environment
                description:
                  type: string
                  description: Detailed description of the workspace
                  example: Main production workspace for customer data processing
                tags:
                  description: Tags associated with the workspace
                  example:
                    - production
                    - customer-data
                  type: array
                  items:
                    type: string
              required:
                - workspaceId
      responses:
        "201":
          description: The Workspace has been successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  workspaceId:
                    type: string
                    description: Unique identifier for the workspace
                    minLength: 4
                    maxLength: 41
                    pattern: ^[a-z0-9]*$
                    example: main
                  region:
                    description: AWS region where the workspace is deployed
                    example: us-west-2
                    allOf:
                      - type: string
                        enum:
                          - us-west-2
                          - us-east-1
                          - us-east-2
                          - eu-central-1
                          - eu-central-2
                          - eu-west-2
                          - ap-southeast-1
                          - ap-southeast-2
                          - ca-central-1
                        description: AWS region where the workspace is deployed
                        x-speakeasy-unknown-values: allow
                  leaderFQDN:
                    type: string
                    description: Fully Qualified Domain Name of the workspace leader
                    example: workspace-leader.example.com
                  state:
                    description: Current state of the workspace
                    example: Active
                    allOf:
                      - type: string
                        enum:
                          - Provisioning
                          - Active
                          - Inactive
                          - Failed
                          - Deprovisioning
                        description: Current state of the workspace
                        x-speakeasy-unknown-values: allow
                  alias:
                    type: string
                    description: User-friendly alias for the workspace
                    example: Production Environment
                  description:
                    type: string
                    description: Detailed description of the workspace
                    example: Main production workspace for customer data processing
                  tags:
                    description: Tags associated with the workspace
                    example:
                      - production
                      - customer-data
                    type: array
                    items:
                      type: string
                required:
                  - workspaceId
                  - region
                  - leaderFQDN
                  - state
        default:
          description: Default error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
      summary: Create a Workspace in the specified Organization
      tags:
        - workspaces
      x-speakeasy-group: workspaces
      x-speakeasy-name-override: create
    get:
      description: Get a list of all Workspaces for the specified Organization.
      operationId: v1.workspaces.listWorkspaces
      parameters:
        - name: organizationId
          required: true
          in: path
          description: The <code>id</code> of the Organization that contains the Workspaces.
          schema:
            type: string
      responses:
        "200":
          description: List of Workspaces has been successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    description: List of workspaces
                    type: array
                    items:
                      type: object
                      properties:
                        workspaceId:
                          type: string
                          description: Unique identifier for the workspace
                          minLength: 4
                          maxLength: 41
                          pattern: ^[a-z0-9]*$
                          example: main
                        region:
                          description: AWS region where the workspace is deployed
                          example: us-west-2
                          allOf:
                            - type: string
                              enum:
                                - us-west-2
                                - us-east-1
                                - us-east-2
                                - eu-central-1
                                - eu-central-2
                                - eu-west-2
                                - ap-southeast-1
                                - ap-southeast-2
                                - ca-central-1
                              description: AWS region where the workspace is deployed
                              x-speakeasy-unknown-values: allow
                        leaderFQDN:
                          type: string
                          description: Fully Qualified Domain Name of the workspace leader
                          example: workspace-leader.example.com
                        state:
                          description: Current state of the workspace
                          example: Active
                          allOf:
                            - type: string
                              enum:
                                - Provisioning
                                - Active
                                - Inactive
                                - Failed
                                - Deprovisioning
                              description: Current state of the workspace
                              x-speakeasy-unknown-values: allow
                        alias:
                          type: string
                          description: User-friendly alias for the workspace
                          example: Production Environment
                        description:
                          type: string
                          description: Detailed description of the workspace
                          example: Main production workspace for customer data processing
                        tags:
                          description: Tags associated with the workspace
                          example:
                            - production
                            - customer-data
                          type: array
                          items:
                            type: string
                      required:
                        - workspaceId
                        - region
                        - leaderFQDN
                        - state
                  count:
                    type: number
                    description: Total number of workspaces
                    example: 5
                required:
                  - items
                  - count
        default:
          description: Default error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
      summary: List all Workspaces for the specified Organization
      tags:
        - workspaces
      x-speakeasy-group: workspaces
      x-speakeasy-name-override: list
  /v1/organizations/{organizationId}/workspaces/{workspaceId}:
    patch:
      description: Update the specified Workspace.
      operationId: v1.workspaces.updateWorkspace
      parameters:
        - name: organizationId
          required: true
          in: path
          description: The <code>id</code> of the Organization that contains the Workspace.
          schema:
            type: string
        - name: workspaceId
          required: true
          in: path
          description: The <code>id</code> of the Workspace to update.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                alias:
                  type: string
                  description: User-friendly alias for the workspace
                  example: Production Environment
                description:
                  type: string
                  description: Detailed description of the workspace
                  example: Main production workspace for customer data processing
                tags:
                  description: Tags associated with the workspace
                  example:
                    - production
                    - customer-data
                  type: array
                  items:
                    type: string
      responses:
        "204":
          description: The Workspace has been successfully updated
        default:
          description: Default error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
      summary: Update a Workspace
      tags:
        - workspaces
      x-speakeasy-group: workspaces
      x-speakeasy-name-override: update
    delete:
      description: Delete the specified Workspace in the specified Organization.
      operationId: v1.workspaces.deleteWorkspace
      parameters:
        - name: organizationId
          required: true
          in: path
          description: The <code>id</code> of the Organization that contains the Workspace.
          schema:
            type: string
        - name: workspaceId
          required: true
          in: path
          description: The <code>id</code> of the Workspace to delete.
          schema:
            type: string
      responses:
        "202":
          description: The Workspace deletion has been accepted
        default:
          description: Default error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
      summary: Delete a Workspace
      tags:
        - workspaces
      x-speakeasy-group: workspaces
      x-speakeasy-name-override: delete
    get:
      description: Get the specified Workspace.
      operationId: v1.workspaces.getWorkspace
      parameters:
        - name: organizationId
          required: true
          in: path
          description: The <code>id</code> of the Organization that contains the Workspace.
          schema:
            type: string
        - name: workspaceId
          required: true
          in: path
          description: The <code>id</code> of the Workspace to get.
          schema:
            type: string
      responses:
        "200":
          description: The Workspace details have been retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  workspaceId:
                    type: string
                    description: Unique identifier for the workspace
                    minLength: 4
                    maxLength: 41
                    pattern: ^[a-z0-9]*$
                    example: main
                  region:
                    description: AWS region where the workspace is deployed
                    example: us-west-2
                    allOf:
                      - type: string
                        enum:
                          - us-west-2
                          - us-east-1
                          - us-east-2
                          - eu-central-1
                          - eu-central-2
                          - eu-west-2
                          - ap-southeast-1
                          - ap-southeast-2
                          - ca-central-1
                        description: AWS region where the workspace is deployed
                        x-speakeasy-unknown-values: allow
                  leaderFQDN:
                    type: string
                    description: Fully Qualified Domain Name of the workspace leader
                    example: workspace-leader.example.com
                  state:
                    description: Current state of the workspace
                    example: Active
                    allOf:
                      - type: string
                        enum:
                          - Provisioning
                          - Active
                          - Inactive
                          - Failed
                          - Deprovisioning
                        description: Current state of the workspace
                        x-speakeasy-unknown-values: allow
                  alias:
                    type: string
                    description: User-friendly alias for the workspace
                    example: Production Environment
                  description:
                    type: string
                    description: Detailed description of the workspace
                    example: Main production workspace for customer data processing
                  tags:
                    description: Tags associated with the workspace
                    example:
                      - production
                      - customer-data
                    type: array
                    items:
                      type: string
                required:
                  - workspaceId
                  - region
                  - leaderFQDN
                  - state
        default:
          description: Default error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
      summary: Get a Workspace
      tags:
        - workspaces
      x-speakeasy-group: workspaces
      x-speakeasy-name-override: get
info:
  title: Cribl.Cloud Public API
  description: Public API for the Cribl.Cloud platform. Powers the Speakeasy SDK.
  version: '1.0'
  contact:
    name: Support
    url: https://portal.support.cribl.io
    email: ""
tags:
  - name: workspaces
    description: Operations related to Workspaces
  - name: health
    description: Operations related to application health status
servers:
  - url: https://gateway.cribl.cloud
security:
  - clientOauth: []
  - bearerAuth: []
x-speakeasy-retries:
  strategy: backoff
  backoff:
    initialInterval: 500
    maxInterval: 60000
    maxElapsedTime: 3600000
    exponent: 1.5
  statusCodes:
    - "502"
    - "503"
    - "504"
  retryConnectionErrors: true
