name: Lint OpenAPI Specs

on:
  pull_request:
    paths:
      - '.speakeasy/lint.yaml'
      - 'specs/control-plane-prerelease.yml'
      - 'specs/control-plane.yml'
      - 'specs/control-plane-stage.yml'
      - 'specs/control-plane-dev.yml'
      - 'specs/mgmt-plane-prerelease.yml'
      - 'specs/mgmt-plane.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint-specs:
    name: Lint specs
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye-slim
    # only run the scheduled event on main; still run on all PRs
    if: ${{ github.event_name != 'schedule' || github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare shell & install deps
        run: |
          ln -sf /bin/bash /bin/sh
          apt-get update && \
          apt-get install -y --no-install-recommends ca-certificates curl sudo unzip && \
          rm -rf /var/lib/apt/lists/*

      - name: Install Speakeasy CLI
        run: curl -fsSL https://raw.githubusercontent.com/speakeasy-api/speakeasy/main/install.sh | sh

      - name: Lint control plane spec (prod)
        run: speakeasy lint openapi -r criblSDK -s specs/control-plane.yml --non-interactive

      - name: Lint control plane spec (stage)
        run: speakeasy lint openapi -r criblSDK -s specs/control-plane-stage.yml --non-interactive

      - name: Lint control plane spec (dev)
        run: speakeasy lint openapi -r criblSDK -s specs/control-plane-dev.yml --non-interactive

      - name: Lint control plane spec (prerelease)
        run: speakeasy lint openapi -r criblSDK -s specs/control-plane-prerelease.yml --non-interactive

      - name: Lint management plane spec (prod)
        run: speakeasy lint openapi -r criblSDK -s specs/mgmt-plane.yml --non-interactive

      - name: Lint management plane spec (prerelease)
        run: speakeasy lint openapi -r criblSDK -s specs/mgmt-plane-prerelease.yml --non-interactive
